SocialMedia/SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    # path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('feed/', include('feed.urls')),
]

SocialMedia/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('login/', views.login_view, name='login'),
    path('', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

SocialMedia/feed/urls.py
from django.urls import path
from . import views

app_name = 'feed'

urlpatterns = [
    path('', views.feed, name='feed'),
    path('post/', views.post_message, name='post_message'),
    path('comment/<int:message_id>/', views.post_comment, name='post_comment'),
    path('delete/<int:message_id>/', views.delete_message, name='delete_message'),
    path('like/<int:message_id>/', views.like_message, name='like_message'),
    path('like/comment/<int:comment_id>/', views.like_comment, name='like_comment'),
]

SocialMedia/accounts/models.py
from django.db import models

# Create your models here.

SocialMedia/feed/models.py
from django.db import models

from django.contrib.auth.models import User

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    likes = models.ManyToManyField(User, related_name='message_likes', blank=True)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    text = models.TextField()
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)

SocialMedia/accounts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('feed:feed')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #login(request, user)
            #return redirect('feed:feed')
            return render(request, 'accounts/message.html', {'form': form})
    else:
        form = UserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    #return redirect('accounts:login')
    return render(request, 'accounts/logout.html')

SocialMedia/feed/views.py

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Message, Comment

@login_required
def feed(request):
    messages = Message.objects.all()
    return render(request, 'feed/feed.html', {'messages': messages})

@login_required
def post_message(request):
    if request.method == 'POST':
        text = request.POST.get('text')
        Message.objects.create(user=request.user, text=text)
    return redirect('feed:feed')

@login_required
def post_comment(request, message_id):
    if request.method == 'POST':
        text = request.POST.get('text')
        message = Message.objects.get(pk=message_id)
        Comment.objects.create(user=request.user, message=message, text=text)
    return redirect('feed:feed')

@login_required
def delete_message(request, message_id):
    message = Message.objects.get(pk=message_id)
    if message.user == request.user:
        message.delete()
    return redirect('feed:feed')

@login_required
def like_message(request, message_id):
    message = Message.objects.get(pk=message_id)
    message.likes.add(request.user)
    return redirect('feed:feed')

@login_required
def like_comment(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    comment.likes.add(request.user)
    return redirect('feed:feed')

SocialMedia/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/styles.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>

   
    <form method="post" action="{% url 'accounts:login' %}">
        <h3>Social Media App</h3>
        
        <h2>Login</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button  type="submit">Login</button>
        <p>Don't have an account? <a href="{% url 'accounts:register' %}">Register</a></p>
    </form>
    
</body>
</html>

SocialMedia/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>
    <h2>You Are Successfully Logged Out</h2>
    <p>Thank you for using our application. <a href="{% url 'accounts:login' %}">Login</a> again if you wish.</p>
</body>
</html>

SocialMedia/templates/accounts/message.html
<h3>Registered Successfully</h3>

<a href="{% url 'accounts:login' %}">Login</a>

SocialMedia/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>
    
    <form method="post" action="{% url 'accounts:register' %}">
        <h2>Register</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Register</button>
        <p>Already have an account? <a href="{% url 'accounts:login' %}">Login</a></p>
    </form>
</body>
</html>

SocialMedia/templates/feed/feed.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feed</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'feed/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>
    <div>
    <div class="header">
        <h2>You can start post , like , comment and delete</h2>
        <h3 id="logoutlink"><a href="{% url 'accounts:logout' %}" >Logout</a></h3>
    </div>
    <form method="post" action="{% url 'feed:post_message' %}">
        {% csrf_token %}
        <textarea name="text" placeholder="Create and post your thought"></textarea>
        <button class="btn btn-primary" type="submit">Post</button>
    </form>

    {% for message in messages %}
        <div>
            <p>{{ message.text }}</p>
            <p>Posted by: {{ message.user.username }}</p>
            <p>Likes: {{ message.likes.count }}</p>
            <form method="post" action="{% url 'feed:like_message' message.id %}">
                {% csrf_token %}
                <button class="btn btn-success" type="submit">Like</button>
            </form>

            {% for comment in message.comment_set.all %}
                <div>
                    <p>{{ comment.text }}</p>
                    <p>Comment by: {{ comment.user.username }}</p>
                    <p>Likes: {{ comment.likes.count }}</p>
                    <form method="post" action="{% url 'feed:like_comment' comment.id %}">
                        {% csrf_token %}
                        <button class="btn btn-info" type="submit">Like</button>
                    </form>
                </div>
            {% endfor %}

            <form method="post" action="{% url 'feed:post_comment' message.id %}">
                {% csrf_token %}
                <textarea name="text" placeholder="Add a comment" required></textarea>
                <button class="btn btn-warning" type="submit">Comment</button>
            </form>

            {% if message.user == request.user %}
                <form method="post" action="{% url 'feed:delete_message' message.id %}">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            {% endif %}
        </div>
    <div>
        <h1>--------------------------------------------------------------------------------------------</h1>
    </div>
    {% endfor %}
    </div>
</body>
</html>
